# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DlgArticleChange.ui'
#
# Created: Wed Oct 16 13:43:05 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(486, 365)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_type1 = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_type1.sizePolicy().hasHeightForWidth())
        self.comboBox_type1.setSizePolicy(sizePolicy)
        self.comboBox_type1.setObjectName(_fromUtf8("comboBox_type1"))
        self.horizontalLayout.addWidget(self.comboBox_type1)
        self.pushButton_addtype1 = QtGui.QPushButton(self.groupBox)
        self.pushButton_addtype1.setObjectName(_fromUtf8("pushButton_addtype1"))
        self.horizontalLayout.addWidget(self.pushButton_addtype1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.comboBox_type2 = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_type2.sizePolicy().hasHeightForWidth())
        self.comboBox_type2.setSizePolicy(sizePolicy)
        self.comboBox_type2.setObjectName(_fromUtf8("comboBox_type2"))
        self.horizontalLayout_2.addWidget(self.comboBox_type2)
        self.pushButton_addtype2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_addtype2.setObjectName(_fromUtf8("pushButton_addtype2"))
        self.horizontalLayout_2.addWidget(self.pushButton_addtype2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_model = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_model.sizePolicy().hasHeightForWidth())
        self.lineEdit_model.setSizePolicy(sizePolicy)
        self.lineEdit_model.setObjectName(_fromUtf8("lineEdit_model"))
        self.horizontalLayout_3.addWidget(self.lineEdit_model)
        self.label_tips = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_tips.sizePolicy().hasHeightForWidth())
        self.label_tips.setSizePolicy(sizePolicy)
        self.label_tips.setText(_fromUtf8(""))
        self.label_tips.setObjectName(_fromUtf8("label_tips"))
        self.horizontalLayout_3.addWidget(self.label_tips)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit_pkg = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pkg.sizePolicy().hasHeightForWidth())
        self.lineEdit_pkg.setSizePolicy(sizePolicy)
        self.lineEdit_pkg.setObjectName(_fromUtf8("lineEdit_pkg"))
        self.horizontalLayout_4.addWidget(self.lineEdit_pkg)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.comboBox_unit = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_unit.sizePolicy().hasHeightForWidth())
        self.comboBox_unit.setSizePolicy(sizePolicy)
        self.comboBox_unit.setObjectName(_fromUtf8("comboBox_unit"))
        self.horizontalLayout_4.addWidget(self.comboBox_unit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.lineEdit_function = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_function.setObjectName(_fromUtf8("lineEdit_function"))
        self.horizontalLayout_5.addWidget(self.lineEdit_function)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_6.addWidget(self.label_10)
        self.lineEdit_pp = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_pp.setObjectName(_fromUtf8("lineEdit_pp"))
        self.horizontalLayout_6.addWidget(self.lineEdit_pp)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_7.addWidget(self.label_8)
        self.plainTextEdit_detail = QtGui.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_detail.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.plainTextEdit_detail.setObjectName(_fromUtf8("plainTextEdit_detail"))
        self.horizontalLayout_7.addWidget(self.plainTextEdit_detail)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.pushButton_add = QtGui.QPushButton(self.groupBox)
        self.pushButton_add.setObjectName(_fromUtf8("pushButton_add"))
        self.horizontalLayout_8.addWidget(self.pushButton_add)
        self.pushButton_cancel = QtGui.QPushButton(self.groupBox)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.horizontalLayout_8.addWidget(self.pushButton_cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "物品信息:", None))
        self.label.setText(_translate("Dialog", "大类名", None))
        self.pushButton_addtype1.setText(_translate("Dialog", "新增", None))
        self.label_9.setText(_translate("Dialog", "小类名", None))
        self.pushButton_addtype2.setText(_translate("Dialog", "新增", None))
        self.label_2.setText(_translate("Dialog", "型号:", None))
        self.label_6.setText(_translate("Dialog", "封装:", None))
        self.label_5.setText(_translate("Dialog", " 单位", None))
        self.label_3.setText(_translate("Dialog", "用途:", None))
        self.label_10.setText(_translate("Dialog", "品牌:", None))
        self.lineEdit_pp.setText(_translate("Dialog", "详细:", None))
        self.label_8.setText(_translate("Dialog", "备注:", None))
        self.pushButton_add.setText(_translate("Dialog", "修改", None))
        self.pushButton_cancel.setText(_translate("Dialog", "取消", None))

