# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DlgRecordModify.ui'
#
# Created: Mon Oct 07 22:48:49 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(648, 281)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.lineEdit_articlename = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_articlename.sizePolicy().hasHeightForWidth())
        self.lineEdit_articlename.setSizePolicy(sizePolicy)
        self.lineEdit_articlename.setObjectName(_fromUtf8("lineEdit_articlename"))
        self.horizontalLayout_8.addWidget(self.lineEdit_articlename)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_articleid = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_articleid.setObjectName(_fromUtf8("lineEdit_articleid"))
        self.horizontalLayout_8.addWidget(self.lineEdit_articleid)
        self.pushButton_new = QtGui.QPushButton(self.groupBox)
        self.pushButton_new.setFlat(False)
        self.pushButton_new.setObjectName(_fromUtf8("pushButton_new"))
        self.horizontalLayout_8.addWidget(self.pushButton_new)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButton_in = QtGui.QRadioButton(self.groupBox)
        self.radioButton_in.setObjectName(_fromUtf8("radioButton_in"))
        self.horizontalLayout_3.addWidget(self.radioButton_in)
        self.radioButton_out = QtGui.QRadioButton(self.groupBox)
        self.radioButton_out.setObjectName(_fromUtf8("radioButton_out"))
        self.horizontalLayout_3.addWidget(self.radioButton_out)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.dateEdit = QtGui.QDateEdit(self.groupBox)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.horizontalLayout_3.addWidget(self.dateEdit)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_count = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_count.setObjectName(_fromUtf8("lineEdit_count"))
        self.horizontalLayout_2.addWidget(self.lineEdit_count)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_price = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_price.setObjectName(_fromUtf8("lineEdit_price"))
        self.horizontalLayout_2.addWidget(self.lineEdit_price)
        self.label_total = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_total.sizePolicy().hasHeightForWidth())
        self.label_total.setSizePolicy(sizePolicy)
        self.label_total.setObjectName(_fromUtf8("label_total"))
        self.horizontalLayout_2.addWidget(self.label_total)
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.label_9)
        self.lineEdit_client = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_client.setEnabled(False)
        self.lineEdit_client.setObjectName(_fromUtf8("lineEdit_client"))
        self.horizontalLayout.addWidget(self.lineEdit_client)
        self.pushButton_selectclient = QtGui.QPushButton(self.groupBox)
        self.pushButton_selectclient.setFlat(False)
        self.pushButton_selectclient.setObjectName(_fromUtf8("pushButton_selectclient"))
        self.horizontalLayout.addWidget(self.pushButton_selectclient)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit_number = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_number.setObjectName(_fromUtf8("lineEdit_number"))
        self.horizontalLayout.addWidget(self.lineEdit_number)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.textEdit_detail = QtGui.QTextEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_detail.sizePolicy().hasHeightForWidth())
        self.textEdit_detail.setSizePolicy(sizePolicy)
        self.textEdit_detail.setMaximumSize(QtCore.QSize(16777215, 80))
        self.textEdit_detail.setObjectName(_fromUtf8("textEdit_detail"))
        self.horizontalLayout_4.addWidget(self.textEdit_detail)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.label_tips = QtGui.QLabel(Dialog)
        self.label_tips.setObjectName(_fromUtf8("label_tips"))
        self.horizontalLayout_6.addWidget(self.label_tips)
        self.pushButton_addtolist = QtGui.QPushButton(Dialog)
        self.pushButton_addtolist.setObjectName(_fromUtf8("pushButton_addtolist"))
        self.horizontalLayout_6.addWidget(self.pushButton_addtolist)
        self.pushButton_reset = QtGui.QPushButton(Dialog)
        self.pushButton_reset.setObjectName(_fromUtf8("pushButton_reset"))
        self.horizontalLayout_6.addWidget(self.pushButton_reset)
        self.pushButton_cancel = QtGui.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.horizontalLayout_6.addWidget(self.pushButton_cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "物品", None))
        self.label_6.setText(_translate("Dialog", "物品型号:", None))
        self.label_8.setText(_translate("Dialog", "物品系统ID:", None))
        self.pushButton_new.setText(_translate("Dialog", "选择物品", None))
        self.radioButton_in.setText(_translate("Dialog", "进货", None))
        self.radioButton_out.setText(_translate("Dialog", "出货", None))
        self.label_4.setText(_translate("Dialog", "  日期", None))
        self.label.setText(_translate("Dialog", "数量:", None))
        self.label_7.setText(_translate("Dialog", "个", None))
        self.label_2.setText(_translate("Dialog", "单价:", None))
        self.label_total.setText(_translate("Dialog", "总金额", None))
        self.label_9.setText(_translate("Dialog", "客户:", None))
        self.pushButton_selectclient.setText(_translate("Dialog", "浏览", None))
        self.label_5.setText(_translate("Dialog", "货单号:", None))
        self.label_3.setText(_translate("Dialog", "说明:", None))
        self.label_tips.setText(_translate("Dialog", "        this display errors", None))
        self.pushButton_addtolist.setText(_translate("Dialog", "修改", None))
        self.pushButton_reset.setText(_translate("Dialog", "重置", None))
        self.pushButton_cancel.setText(_translate("Dialog", "取消", None))

